### ISSUE TITLE
LLMs/Transformers Case Study

### ISSUE THREAD

**Issue by panoskyriakis** [NevronAI/MetisFL#42]
### 📚 The doc issue

The current case-studies and examples of MetisFL contain introductory stuff (quickstart w/ TF, Torch and SKLearn) as well as a more advanced example on GenAI using Torch and the Celeba dataset. 

We want to expand our examples by implementing an LLM case-study using the transformers library. The exact problem and dataset to be used is open-ended. One simple idea is the [Sentiment classification](https://huggingface.co/blog/sentiment-analysis-python) problem by the HF team. However, any other problems or datasets are also welcome!

If you are looking for ideas on how to structure the code and the ReadMe, the current [examples](https://github.com/NevronAI/MetisFL/tree/main/examples) are a great starting point!

Happy coding  🎉

**Comment by mertbozkir** [comment]
Hello Panos, I learned about MetisFL today. 

I would love to work on this issue, how does text generation use case sounds to you? I'm a little bit in my schedule, but I can commit after October 15th! 🤠

**Comment by panoskyriakis** [comment]
Hi Mert! 

Thanks a lot for your eagerness to contribute! I think there's someone doing something on this issue as well. Please join our slack and I'll get you connected to them so you can work together. I can find them here on github for some reason.

**Comment by nkanak** [comment]
Hey @mertbozkir!

I have been working on a similar example, i.e. classification with a BERT-based model using the *transformers* library. I expect that the example will be ready by this Friday. We can easily adapt the code afterwards and use an LLM model like [Llama 2](https://huggingface.co/meta-llama/Llama-2-7b).

Please, join the slack channel and feel free to reach out to me!
